#!/usr/bin/env python3
"""
Generate a declarative NPC tier map from the unified NPC asset index.

This script reads:
- an NPC asset index generated by `scrape_hytale_npc_assets.py`
- a declarative tiering config JSON

and produces:
- a gameplay-oriented `npc-tier-map.json`

The config is intentionally data-driven:
- tier definitions live in JSON
- rule groups live in JSON
- post modifiers live in JSON

Example:
    python3 tools/generate_npc_tier_map.py \
      --index docs/npc-assets-index.json \
      --config tools/npc_tiering_rules.json \
      --output docs/npc-tier-map.json \
      --pretty
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_INDEX_PATH = "docs/npc-assets-index.json"
DEFAULT_OUTPUT_PATH = "docs/npc-tier-map.json"
DEFAULT_CONFIG_PATH = "tools/npc_tiering_rules.json"


class TieringError(Exception):
    pass


@dataclass(frozen=True)
class TierDecision:
    tier: int
    drop_chance: float
    base_quantity: int
    quantity: int
    reasons: list[str]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def clamp_int(value: int, minimum: int, maximum: int) -> int:
    return max(minimum, min(maximum, value))


def clamp_float(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))


def load_json(path: Path) -> dict[str, Any]:
    try:
        content = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise TieringError(f"File not found: {path}") from exc
    except OSError as exc:
        raise TieringError(f"Failed to read file: {path}") from exc

    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        raise TieringError(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise TieringError(f"Expected JSON object in {path}")
    return data


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a declarative NPC tier map from npc-assets-index.json."
    )
    parser.add_argument(
        "--index",
        default=DEFAULT_INDEX_PATH,
        help=f"Path to the NPC asset index JSON (default: {DEFAULT_INDEX_PATH}).",
    )
    parser.add_argument(
        "--config",
        default=DEFAULT_CONFIG_PATH,
        help=f"Path to the declarative tiering rules JSON (default: {DEFAULT_CONFIG_PATH}).",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output JSON file path (default: {DEFAULT_OUTPUT_PATH}).",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print the generated JSON.",
    )
    return parser.parse_args(argv)


def ensure_parent_directory(path: Path) -> None:
    if path.parent and not path.parent.exists():
        path.parent.mkdir(parents=True, exist_ok=True)


def lower_tokens_from_values(values: list[str]) -> set[str]:
    tokens: set[str] = set()
    for value in values:
        text = str(value).replace("-", "_").replace(" ", "_").lower()
        if not text:
            continue
        tokens.add(text)
        for part in text.split("_"):
            if part:
                tokens.add(part)
    return tokens


def get_flags(npc: dict[str, Any]) -> dict[str, bool]:
    raw = npc.get("flags", {})
    if not isinstance(raw, dict):
        return {}
    return {str(key): bool(value) for key, value in raw.items()}


def get_attitudes(npc: dict[str, Any]) -> set[str]:
    raw = npc.get("inferred_attitudes", [])
    if not isinstance(raw, list):
        return set()
    return {str(value) for value in raw}


def get_primary_family(npc: dict[str, Any]) -> str | None:
    value = npc.get("primary_family")
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def get_variants(npc: dict[str, Any]) -> list[str]:
    raw = npc.get("variants", [])
    if not isinstance(raw, list):
        return []
    return [str(value) for value in raw]


def get_interaction_names(npc: dict[str, Any]) -> list[str]:
    raw = npc.get("interaction_names", [])
    if not isinstance(raw, list):
        return []
    return [str(value) for value in raw]


def get_taxonomy_segments(npc: dict[str, Any]) -> dict[str, list[str]]:
    raw = npc.get("taxonomy", {})
    if not isinstance(raw, dict):
        return {}
    result: dict[str, list[str]] = {}
    for key, value in raw.items():
        if isinstance(value, list):
            result[str(key)] = [str(item) for item in value]
    return result


def collect_npc_keywords(npc: dict[str, Any]) -> set[str]:
    values: list[str] = []

    npc_id = npc.get("npc_id")
    normalized_id = npc.get("normalized_id")
    if npc_id is not None:
        values.append(str(npc_id))
    if normalized_id is not None:
        values.append(str(normalized_id))

    values.extend(get_variants(npc))
    values.extend(get_interaction_names(npc))

    taxonomy = get_taxonomy_segments(npc)
    for segment_list in taxonomy.values():
        values.extend(segment_list)

    return lower_tokens_from_values(values)


def get_context(npc: dict[str, Any]) -> dict[str, Any]:
    return {
        "npc_id": str(npc.get("npc_id") or ""),
        "normalized_id": str(npc.get("normalized_id") or ""),
        "primary_family": get_primary_family(npc),
        "flags": get_flags(npc),
        "attitudes": get_attitudes(npc),
        "keywords": collect_npc_keywords(npc),
        "variants": get_variants(npc),
        "interaction_names": get_interaction_names(npc),
    }


def any_flag_true(flags: dict[str, bool], names: list[str]) -> bool:
    return any(flags.get(name, False) for name in names)


def all_flags_true(flags: dict[str, bool], names: list[str]) -> bool:
    return all(flags.get(name, False) for name in names)


def any_attitude_present(attitudes: set[str], names: list[str]) -> bool:
    return any(name in attitudes for name in names)


def all_attitudes_present(attitudes: set[str], names: list[str]) -> bool:
    return all(name in attitudes for name in names)


def any_keyword_present(keywords: set[str], names: list[str]) -> bool:
    lowered = {str(name).lower() for name in names}
    return any(name in keywords for name in lowered)


def all_keywords_present(keywords: set[str], names: list[str]) -> bool:
    lowered = {str(name).lower() for name in names}
    return all(name in keywords for name in lowered)


def match_rule(rule_match: dict[str, Any], context: dict[str, Any]) -> bool:
    npc_id = context["npc_id"]
    primary_family = context["primary_family"]
    flags = context["flags"]
    attitudes = context["attitudes"]
    keywords = context["keywords"]

    npc_ids = [str(value) for value in rule_match.get("npc_ids", []) or []]
    if npc_ids and npc_id not in npc_ids:
        return False

    primary_families = [
        str(value) for value in rule_match.get("primary_families", []) or []
    ]
    if primary_families and primary_family not in primary_families:
        return False

    any_flags_true_match = [
        str(value) for value in rule_match.get("any_flags_true", []) or []
    ]
    if any_flags_true_match and not any_flag_true(flags, any_flags_true_match):
        return False

    all_flags_true_match = [
        str(value) for value in rule_match.get("all_flags_true", []) or []
    ]
    if all_flags_true_match and not all_flags_true(flags, all_flags_true_match):
        return False

    any_attitudes_match = [
        str(value) for value in rule_match.get("any_attitudes", []) or []
    ]
    if any_attitudes_match and not any_attitude_present(attitudes, any_attitudes_match):
        return False

    all_attitudes_match = [
        str(value) for value in rule_match.get("all_attitudes", []) or []
    ]
    if all_attitudes_match and not all_attitudes_present(
        attitudes, all_attitudes_match
    ):
        return False

    any_keywords_match = [
        str(value) for value in rule_match.get("any_keywords", []) or []
    ]
    if any_keywords_match and not any_keyword_present(keywords, any_keywords_match):
        return False

    all_keywords_match = [
        str(value) for value in rule_match.get("all_keywords", []) or []
    ]
    if all_keywords_match and not all_keywords_present(keywords, all_keywords_match):
        return False

    return True


def group_is_locking(group_name: str) -> bool:
    return group_name == "explicit_overrides"


def apply_rule_result(
    current_tier: int | None,
    current_drop_chance: float | None,
    current_base_quantity: int | None,
    group_name: str,
    result: dict[str, Any],
    reasons: list[str],
    default_reason: str,
) -> tuple[int | None, float | None, int | None]:
    updated_tier = current_tier
    updated_drop_chance = current_drop_chance
    updated_base_quantity = current_base_quantity

    if "tier" in result:
        next_tier = int(result["tier"])
        if group_is_locking(group_name):
            updated_tier = next_tier
        elif updated_tier is None:
            updated_tier = next_tier
        else:
            updated_tier = max(updated_tier, next_tier)

    if "drop_chance" in result:
        next_drop_chance = float(result["drop_chance"])
        if group_is_locking(group_name):
            updated_drop_chance = next_drop_chance
        elif updated_drop_chance is None:
            updated_drop_chance = next_drop_chance
        else:
            updated_drop_chance = max(updated_drop_chance, next_drop_chance)

    if "base_quantity" in result:
        next_base_quantity = int(result["base_quantity"])
        if group_is_locking(group_name):
            updated_base_quantity = next_base_quantity
        elif updated_base_quantity is None:
            updated_base_quantity = next_base_quantity
        else:
            updated_base_quantity = max(updated_base_quantity, next_base_quantity)

    reasons.append(str(result.get("reason") or default_reason))
    return updated_tier, updated_drop_chance, updated_base_quantity


def normalize_tier_definitions(config: dict[str, Any]) -> dict[str, dict[str, Any]]:
    raw = config.get("tier_definitions")
    if raw is None:
        raw = config.get("tiers", {})
    if not isinstance(raw, dict):
        raise TieringError("Config must contain an object under 'tier_definitions'.")

    normalized: dict[str, dict[str, Any]] = {}
    for key, value in raw.items():
        if not isinstance(value, dict):
            raise TieringError(f"Tier definition '{key}' must be an object.")
        normalized[str(key)] = value
    if not normalized:
        raise TieringError("Config contains no tier definitions.")
    return normalized


def available_tier_bounds(
    tier_definitions: dict[str, dict[str, Any]],
) -> tuple[int, int]:
    try:
        values = [int(key) for key in tier_definitions.keys()]
    except ValueError as exc:
        raise TieringError(
            "Tier definition keys must be integers encoded as strings."
        ) from exc
    return min(values), max(values)


def apply_rule_groups(
    context: dict[str, Any],
    rule_group_names: list[str],
    grouped_rules: dict[str, list[dict[str, Any]]],
    reasons: list[str],
) -> tuple[int | None, float | None, int | None]:
    tier: int | None = None
    drop_chance: float | None = None
    base_quantity: int | None = None

    for group_name in rule_group_names:
        rules = grouped_rules.get(group_name, [])
        for rule in rules:
            rule_match = rule.get("match", {})
            if not isinstance(rule_match, dict):
                continue
            if not match_rule(rule_match, context):
                continue

            result = rule.get("result", {})
            if not isinstance(result, dict):
                continue

            tier, drop_chance, base_quantity = apply_rule_result(
                current_tier=tier,
                current_drop_chance=drop_chance,
                current_base_quantity=base_quantity,
                group_name=group_name,
                result=result,
                reasons=reasons,
                default_reason=str(rule.get("name") or group_name),
            )

            if group_is_locking(group_name):
                return tier, drop_chance, base_quantity

    return tier, drop_chance, base_quantity


def apply_post_modifiers(
    context: dict[str, Any],
    post_modifiers: list[dict[str, Any]],
    tier: int,
    drop_chance: float,
    base_quantity: int,
    quantity: int,
    reasons: list[str],
) -> tuple[int, float, int, int]:
    current_tier = tier
    current_drop_chance = drop_chance
    current_base_quantity = base_quantity
    current_quantity = quantity

    for modifier in post_modifiers:
        if not bool(modifier.get("enabled", True)):
            continue

        rule_match = modifier.get("match", {})
        if not isinstance(rule_match, dict):
            continue
        if not match_rule(rule_match, context):
            continue

        effect = modifier.get("effect", {})
        if not isinstance(effect, dict):
            continue

        reason = str(modifier.get("reason") or modifier.get("name") or "post_modifier")

        if "force_tier" in effect:
            current_tier = int(effect["force_tier"])
            reasons.append(f"{reason} (force_tier)")
        if "force_drop_chance" in effect:
            current_drop_chance = float(effect["force_drop_chance"])
            reasons.append(f"{reason} (force_drop_chance)")
        if "force_base_quantity" in effect:
            current_base_quantity = int(effect["force_base_quantity"])
            current_quantity = current_base_quantity
            reasons.append(f"{reason} (force_base_quantity)")
        if "add_quantity" in effect:
            current_quantity += int(effect["add_quantity"])
            reasons.append(f"{reason} (add_quantity:{int(effect['add_quantity']):+d})")

    return current_tier, current_drop_chance, current_base_quantity, current_quantity


def decide_tier(npc: dict[str, Any], config: dict[str, Any]) -> TierDecision:
    defaults = config.get("defaults", {})
    if not isinstance(defaults, dict):
        defaults = {}

    tier_definitions = normalize_tier_definitions(config)
    tier_min, tier_max = available_tier_bounds(tier_definitions)

    context = get_context(npc)
    reasons: list[str] = []

    tier_order_raw = config.get("tier_order", [])
    if not isinstance(tier_order_raw, list):
        raise TieringError("Config field 'tier_order' must be a list.")

    rule_groups_raw = config.get("rules", {})
    if not isinstance(rule_groups_raw, dict):
        raise TieringError("Config field 'rules' must be an object.")

    grouped_rules: dict[str, list[dict[str, Any]]] = {}
    for group_name, group_rules in rule_groups_raw.items():
        if not isinstance(group_rules, list):
            continue
        grouped_rules[str(group_name)] = [
            rule for rule in group_rules if isinstance(rule, dict)
        ]

    tier, drop_chance, base_quantity = apply_rule_groups(
        context=context,
        rule_group_names=[str(name) for name in tier_order_raw],
        grouped_rules=grouped_rules,
        reasons=reasons,
    )

    if tier is None:
        tier = int(defaults.get("tier", 1))
        reasons.append(f"fallback:tier:{tier}")

    tier = clamp_int(int(tier), tier_min, tier_max)

    tier_config = tier_definitions.get(str(tier), {})
    if not isinstance(tier_config, dict):
        tier_config = {}

    if drop_chance is None:
        drop_chance = float(
            tier_config.get("drop_chance", defaults.get("drop_chance", 0.35))
        )
    if base_quantity is None:
        base_quantity = int(
            tier_config.get("base_quantity", defaults.get("base_quantity", 1))
        )

    quantity = base_quantity

    post_modifiers_raw = config.get("post_modifiers", [])
    if not isinstance(post_modifiers_raw, list):
        post_modifiers_raw = []

    tier, drop_chance, base_quantity, quantity = apply_post_modifiers(
        context=context,
        post_modifiers=[item for item in post_modifiers_raw if isinstance(item, dict)],
        tier=tier,
        drop_chance=drop_chance,
        base_quantity=base_quantity,
        quantity=quantity,
        reasons=reasons,
    )

    tier = clamp_int(int(tier), tier_min, tier_max)
    drop_chance = clamp_float(float(drop_chance), 0.0, 1.0)

    validation = config.get("validation", {})
    if not isinstance(validation, dict):
        validation = {}

    allowed_tiers = validation.get("allowed_tiers")
    if isinstance(allowed_tiers, list):
        allowed_tier_values = {int(value) for value in allowed_tiers}
        if tier not in allowed_tier_values:
            raise TieringError(
                f"NPC '{context['npc_id']}' resolved to disallowed tier {tier}."
            )

    base_quantity_range = validation.get("base_quantity_range", {})
    if not isinstance(base_quantity_range, dict):
        base_quantity_range = {}
    quantity_min = int(base_quantity_range.get("min", 0))
    quantity_max = int(base_quantity_range.get("max", 99))

    current_base_quantity = clamp_int(int(base_quantity), quantity_min, quantity_max)
    current_quantity = clamp_int(int(quantity), quantity_min, quantity_max)

    drop_chance_range = validation.get("drop_chance_range", {})
    if not isinstance(drop_chance_range, dict):
        drop_chance_range = {}
    drop_min = float(drop_chance_range.get("min", 0.0))
    drop_max = float(drop_chance_range.get("max", 1.0))
    current_drop_chance = clamp_float(float(drop_chance), drop_min, drop_max)

    return TierDecision(
        tier=tier,
        drop_chance=current_drop_chance,
        base_quantity=current_base_quantity,
        quantity=current_quantity,
        reasons=reasons,
    )


def summarize_tier_map(npc_entries: list[dict[str, Any]]) -> dict[str, Any]:
    by_tier: dict[str, int] = {}
    by_family: dict[str, int] = {}
    with_drop = 0

    for entry in npc_entries:
        tier_key = str(entry["tier"])
        by_tier[tier_key] = by_tier.get(tier_key, 0) + 1

        family = entry.get("primary_family") or "NONE"
        by_family[str(family)] = by_family.get(str(family), 0) + 1

        if float(entry.get("drop_chance", 0.0)) > 0.0:
            with_drop += 1

    return {
        "npc_count": len(npc_entries),
        "dropping_npc_count": with_drop,
        "by_tier": dict(sorted(by_tier.items(), key=lambda item: int(item[0]))),
        "by_primary_family": dict(sorted(by_family.items())),
    }


def build_tier_map(
    index_data: dict[str, Any], config: dict[str, Any]
) -> dict[str, Any]:
    npcs = index_data.get("npcs", [])
    if not isinstance(npcs, list):
        raise TieringError("Invalid index file: 'npcs' must be a list.")

    tier_definitions = normalize_tier_definitions(config)
    result_entries: list[dict[str, Any]] = []

    for npc in npcs:
        if not isinstance(npc, dict):
            continue

        decision = decide_tier(npc, config)

        entry: dict[str, Any] = {
            "npc_id": npc.get("npc_id"),
            "normalized_id": npc.get("normalized_id"),
            "primary_family": npc.get("primary_family"),
            "inferred_attitudes": npc.get("inferred_attitudes", []),
            "flags": npc.get("flags", {}),
            "variants": npc.get("variants", []),
            "tier": decision.tier,
            "tier_label": tier_definitions.get(str(decision.tier), {}).get(
                "label", "unknown"
            ),
            "drop_chance": decision.drop_chance,
            "base_quantity": decision.base_quantity,
            "quantity": decision.quantity,
            "reasons": decision.reasons,
        }

        interaction_names = npc.get("interaction_names")
        if isinstance(interaction_names, list) and interaction_names:
            entry["interaction_names"] = interaction_names

        result_entries.append(entry)

    result_entries.sort(key=lambda item: str(item.get("normalized_id") or ""))

    return {
        "generated_at": utc_now_iso(),
        "source_index_generated_at": index_data.get("generated_at"),
        "source_index_path_version": index_data.get("rules_path_version"),
        "config_version": config.get("version"),
        "summary": summarize_tier_map(result_entries),
        "tiers": tier_definitions,
        "npcs": result_entries,
    }


def write_json(path: Path, data: dict[str, Any], pretty: bool) -> None:
    ensure_parent_directory(path)
    if pretty:
        text = json.dumps(data, ensure_ascii=False, indent=2)
        text += "\n"
    else:
        text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    path.write_text(text, encoding="utf-8")


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    index_path = Path(args.index).expanduser()
    config_path = Path(args.config).expanduser()
    output_path = Path(args.output).expanduser()

    try:
        index_data = load_json(index_path)
        config = load_json(config_path)
        tier_map = build_tier_map(index_data, config)
        write_json(output_path, tier_map, pretty=bool(args.pretty))

        summary = tier_map.get("summary", {})
        print(
            (
                f"Wrote NPC tier map to {output_path} "
                f"({summary.get('npc_count', 0)} NPCs, "
                f"{summary.get('dropping_npc_count', 0)} with drops)"
            ),
            file=sys.stderr,
        )
        return 0
    except TieringError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except Exception as exc:
        print(f"Unexpected error: {exc}", file=sys.stderr)
        return 3


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
